#include <bits/stdc++.h>
using namespace std;
#define FOR(i, l, r) for(size_t i = (l); i < (r); ++i)
#define rep(i, n) for(int i = 0; i < (int)(n); i++)
#define rrep(i, n) for(int i = (n)-1; i >= 0; --i)
#define rfor(v, vec) for(auto &v : (vec))
#define itrloop(itr, begin, end) for(auto itr = (begin); itr != end; ++itr)
#define crfor(v, vec) for(const auto &v : (vec))
#define all(x) x.begin(), x.end()
#define call(x) x.cbegin(), x.cend()
#define rall(x) x.rbegin(), x.rend()
#define ull unsigned long long
#define ll long long
#define ul unsigned long

const string YES = "Yes";
const string NO = "No";

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
bool is_repeated(const string &str) {
    for(int i = 0; i < str.size() / 2; ++i) {
        if(str[i] != str[str.size() - i - 1])
            return false;
    }
    return true;
}
int main() {
    string N;
    cin >> N;
    reverse(all(N));
    bool ans = is_repeated(N);
    if(ans) {
        cout << YES << endl;
        return 0;
    }
    rep(i, 10) {
        N += '0';
        if(is_repeated(N)) {
            ans = true;
            break;
        }
    }
    cout << (ans ? YES : NO) << endl;

    return 0;
}
