#include <bits/stdc++.h>
using namespace std;
#define FOR(i, l, r) for(size_t i = (l); i < (r); ++i)
#define rep(i, n) for(int i = 0; i < (int)(n); i++)
#define rrep(i, n) for(int i = (n)-1; i >= 0; --i)
#define rfor(v, vec) for(auto &v : (vec))
#define itrloop(itr, begin, end) for(auto itr = (begin); itr != end; ++itr)
#define crfor(v, vec) for(const auto &v : (vec))
#define all(x) x.begin(), x.end()
#define call(x) x.cbegin(), x.cend()
#define rall(x) x.rbegin(), x.rend()
#define ull unsigned long long
#define ll long long
#define ul unsigned long
#define INF 1001001001ll

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
    long long N;
    scanf("%lld", &N);
    long long W;
    scanf("%lld", &W);
    ll max_v = 100000;
    std::vector< long long > w(N + 1);
    std::vector< long long > v(N + 1);
    for(int i = 1; i <= N; i++) {
        scanf("%lld", &w[i]);
        scanf("%lld", &v[i]);
    }

    vector< ll > dp(max_v + 1, INF);

    dp[0] = 0;
    FOR(i, 1, N + 1) {
        rep(j, max_v + 1) {
            dp[j] = (j >= v[i]) ? min(dp[j], dp[j - v[i]] + w[i]) : dp[j];
        }
    }
    ll ans = max_v;
    while(dp[ans] > W)
        --ans;
    cout << ans << endl;

    return 0;
}
