#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> h, std::vector<long long> u, std::vector<long long> v, long long K, std::vector<long long> s, std::vector<long long> t){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> h(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&h[i]);
    }
    std::vector<long long> u(N-1);
    std::vector<long long> v(N-1);
    for(int i = 0 ; i < N-1 ; i++){
        scanf("%lld",&u[i]);
        scanf("%lld",&v[i]);
    }
    long long K;
    scanf("%lld",&K);
    std::vector<long long> s(K);
    std::vector<long long> t(K);
    for(int i = 0 ; i < K ; i++){
        scanf("%lld",&s[i]);
        scanf("%lld",&t[i]);
    }
    solve(N, std::move(h), std::move(u), std::move(v), K, std::move(s), std::move(t));
    return 0;
}
